name: respanno-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.11
  - numpy>=1.21
  - scipy>=1.7
  - librosa>=0.9
  - pyqt5>=5.15
  - pyqtgraph>=0.13
  - scikit-learn>=1.0
  - lightgbm>=3.3
  - pip
  - pip:
    - sounddevice>=0.4
